### ISSUE TITLE
Emer and Peer genesis

### ISSUE THREAD

**Issue by SoraKohaku** [liveblockchain/genesisgen#1]
not work in this case....

`fruitd: chainparams.cpp:207: CMainParams::CMainParams(): Assertion `consensus.hashGenesisBlock == uint256S("0x000000004421dbf94542db9b40e4bc60da8ce6b793f00924cadf5677d364a6a1")' failed. Aborted`

**Comment by auscash** [comment]
A little more context would be helpful.

How did you run the genesisgen program and for what crypto?

**Comment by SoraKohaku** [comment]
I'm, at last, used older code. and upgrade its features.
